herStory/herStory/urls.py
from django.contrib import admin
from django.urls import path, include
#from posts import views
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", home, name='home'), 
    # [develop] core.urls 앱 단위로 분리 > 탐험,퀴즈,게시판 / 로그인,마이페이지 등 연결?

    path('users/', include('users.urls', namespace='users')),
    # 소셜 로그인
    path('authaccounts/', include('allauth.urls')),
    path('posts/', include('posts.urls')),
    path('quizzes/', include('quizzes.urls')), # 퀴즈 추가해서 충돌 > 병합하면 ok
    path('history/', include('history.urls')),
]

herStory/history/urls.py
from django.urls import path
from . import views

app_name = 'history'

urlpatterns = [
    path('card/', views.card_intro, name='card_intro'),
    path('card/random/', views.random_card, name='random_card'),
    path('card/save/<int:card_id>/', views.save_card, name='save_card'),
    path('card/<int:card_id>/', views.card_detail, name='card_detail'),
]

herStory/posts/urls.py
from django.urls import path
from .views import *

app_name = 'posts'

urlpatterns = [
    #인덱스 페이지 사용 안 함 path('', index, name='index'),
    path('create/', create, name='create'),
    path('detail/<int:id>/', detail, name='detail'),
    path('update/<int:id>/', update, name='update'),
    path('delete/<int:id>/', delete, name='delete'),
    path('create-comment/<int:post_id>/', create_comment, name='create-comment'),
    path('comments/<int:comment_id>/delete/', delete_comment, name='delete-comment'),
    path('comments/<int:comment_id>/update/', update_comment, name='update-comment'),
    path('like/<int:post_id>/', like, name='like'),
    path('board/',board, name='board'),
    path('category/<int:category_id>/', category, name='category'),
    path('search/', search, name='search')
]

'''
    path('category/<slug:slug>/', category, name='category'),
    path('scrap/<int:post_id>/', scrap, name='scrap'),
'''

herStory/quizzes/urls.py
from django.urls import path
from .views import *

app_name = 'quizzes'

urlpatterns = [
    path('', quiz_index, name='quiz_index'),
    path('school_selection/', school_selection, name='school_selection'),
    path('quiz_detail/', quiz_detail, name='quiz_detail'),
    path('submit_answer/', submit_answer, name='submit_answer'),
    path('quiz_result/', quiz_result, name='quiz_result'),
    path('ranking/',ranking, name='ranking'),
    path('explanation/<int:quiz_id>/', explanation, name='explanation'),
    path('quiz-result/', quiz_result, name='quiz_result'),
    path('quiz_result_redirect/', quiz_result_redirect_view, name='quiz_result_redirect'),
]

herStory/users/urls.py
from django.urls import path, include
from users import views

# 앱 단위의 네임스페이스 정의
app_name = "users"

urlpatterns = [
    # 소셜 로그인 하자마자 바로 회원가입이 되는 구조라서 이 부분은 주석처리 할게요!
    # path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete_account, name='delete_account'),
    path('mypage/', views.mypage, name='mypage'),
    path('mypage/edit/', views.edit_profile, name='edit_profile'),
    
    path('my-cards/', views.my_saved_cards, name='my_cards'),
    path('my-cards/<int:card_id>/', views.saved_card_detail, name='my_cards_detail'),
    
    path('mypage/archives/', views.my_archives, name='my_archives'),

       #path('redirect/', views.redirect_after_login, name='redirect'),
]

herStory/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager

# 장고에서 사용자를 생성/관리하는 커스텀 매니저 클래스
class UserManager(BaseUserManager):
    ## 일반 사용자 생성
    def create_user(self, email, username=None):
        # 이메일 필수 입력으로 설정
        if not email:
            raise ValueError('이메일은 필수입니다.')
        email = self.normalize_email(email)
        # 이메일 주소 정규화
        user = self.model(email=email, username=username)
        # 소셜 로그인이면 비밀번호 필요 X -> 입력을 못하게 아예 차단
        ### 보니까 저희 서비스가 소셜 로그인만 가능하게 하더라구요! 그래서 비밀번호 애초에 없게 코딩했습니다 :)
        user.set_unusable_password()
        # DB에 저장 후 반환
        user.save(using=self._db)
        return user

    # python manage.py createsuperuser 실행 시 작동하는 함수
    ## 무조건 이메일 입력 필수
    ### User 모델에서 AbstractBaseUser 상속 받는데, 기본 유저 생성 메소드가 정의 안되어있기에 함수선언 필수
    def create_superuser(self, email, username=None, password=None):
        user = self.create_user(email=email, username=username)
        user.set_password(password)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user
    
class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=20, null=False)
    email = models.EmailField(max_length=70, unique=True, null=False)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.email

herStory/users/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']
        labels = {
            'username': '성함',
            'email':'이메일',
        }
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '성함'}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '이메일'}),
        }

herStory/users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from .forms import UserUpdateForm
from history.models import UserSavedCard, HistoryCard
from posts.models import Post, Comment
from django.urls import reverse
from django.contrib import messages
from django.core.paginator import Paginator

def signup(request):
    return render(request, 'users/signup.html')

def login(request):
    return render(request, 'users/login.html')

def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect('home')

@login_required
def delete_account(request):
    if request.method == 'POST':
        request.user.delete()
        logout(request)
        messages.success(request, "회원 탈퇴가 완료되었습니다.")
        return redirect('home')
    return render(request, 'users/delete_confirm.html')

@login_required
def mypage(request):
    return render(request, 'users/mypage.html', {
        'user' : request.user
    })

@login_required
def edit_profile(request):
    user = request.user

    if request.method == 'POST':
        form = UserUpdateForm(request.POST, instance=user)
        if form.is_valid():
            if not form.cleaned_data.get('username'):
                form.add_error('username', "이름은 필수입니다.")
            else:
                form.save()
                return redirect('users:mypage')
    else:
        form = UserUpdateForm(instance=user)

    return render(request, 'users/edit_profile.html', {'form': form})

@login_required
def my_saved_cards(request):
    card_list = UserSavedCard.objects.filter(user=request.user).select_related('card').order_by('-saved_at')
    paginator = Paginator(card_list, 7)  # 한 페이지에 7개씩
    page_number = request.GET.get('page')
    saved_cards = paginator.get_page(page_number)
    return render(request, 'users/my_cards.html', {'saved_cards': saved_cards})

@login_required
def saved_card_detail(request, card_id):
    card = get_object_or_404(HistoryCard, id=card_id)
    return render(request, 'users/my_cards_detail.html', {'card': card})

@login_required
def my_archives(request):
    my_posts = Post.objects.filter(user=request.user).order_by('-created_at')
    my_comments = Comment.objects.filter(author=request.user).order_by('-created_at')
    return render(request, 'users/my_archives.html', {
        'my_posts': my_posts,
        'my_comments': my_comments,
    })

herStory/users/templates/users/login.html
{% load socialaccount %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Era Echo - Quiz</title>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Pretendard:wght@100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'login/css/Login.css' %}">
    <script src="{% static 'login/js/Login.js' %}"></script>
  </head>
<body>

<div class="app-container">
    
    <header class="header">
      <img src="{% static 'home/image/mainLogo.svg' %}" class="main-logo" />
        <button class="menu-toggle" id="menuToggle">
          <img src="{% static 'quizzes/image/Menu.svg' %}">
        </button>
        <nav class="menu" id="menu">
          <ul>
          {% if user.is_authenticated %}
            <li>{{ user.username }}님 환영합니다!</li>
            <li class='menu-link' data-url="{% url 'users:logout' %}">로그아웃</li>
          {% else %}
            <li class='menu-link' data-url="{% url 'users:login' %}">로그인</li>
          {% endif %}
          {% if user.is_authenticated %}
          <div class="divider"></div>
            <li class="menu-link" data-url="{% url 'history:card_intro' %}">과거를 알다: 랜덤 인물 카드</li>
            <li class="menu-link" data-url="{% url 'quizzes:quiz_index' %}">지금을 묻다: 역사 퀴즈</li>
            <li class="menu-link" data-url="/posts/category/1/">미래를 잇다: 커뮤니티</li>
            <li class="menu-link" data-url="{% url 'users:mypage' %}">마이페이지</li>
          {% endif %}
        </ul>
        </nav>
      </header>

<div class="for-zindex">
<!-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ -->

   <div class="now">
        <div class="main-ment">
          <img class="line-1" src="{% static 'login/image/Line.svg' %}" />
          <div class="text-wrapper">
            간편 로그인
          </div>
        </div>
        <img class="image-removebg" src="{% static 'login/image/Loginbackground.png' %}" />
    </div>

    <div class="loginOption">
      <a href="{% provider_login_url 'google' %}">
        <button type="submit" class="Google">
            <img class="G_logo" src="{% static 'login/image/googleLogo.svg' %}" />
            <span class="Google-text">구글 계정으로 시작</span>
        </button>
      </a>
      <a href="{% provider_login_url 'kakao' %}">
        <button type="submit" class="Kakao">
            <img class="K_logo" src="{% static 'login/image/KakaoLogo.svg' %}" />
            <span class="Kakao-text">카카오 계정으로 시작</span>
        </button>
      </a>
    </div>
  
</div>
</body>
</html>

herStory/users/templates/users/my_archives.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Era Echo - mypage</title>
    <link rel="stylesheet" href="{% static 'home/css/header.css' %}" />
    <link rel="stylesheet" href="{% static 'home/css/mypage.css' %}" />
    <link rel="stylesheet" href="{% static 'home/css/button.css' %}" />
  </head>
  <body>
    <header class="header">
      <a href="{% url 'home' %}">
        <img src="{% static 'home/image/mainLogo.svg' %}" class="main-logo" />
      </a>
      <button class="menu-toggle" id="menuToggle">&#9776;</button>
      <nav class="menu" id="menu">
        <ul>
          {% if user.is_authenticated %}
            <li>{{ user.username }}님 환영합니다!</li>
            <li class='menu-link' data-url="{% url 'users:logout' %}">로그아웃</li>
          {% else %}
            <li class='menu-link' data-url="{% url 'users:login' %}">로그인</li>
          {% endif %}
          {% if user.is_authenticated %}
          <div class="divider"></div>
          <li class="menu-link" data-url="{% url 'history:card_intro' %}">과거를 알다: 랜덤 인물 카드</li>
          <li class="menu-link" data-url="{% url 'quizzes:quiz_index' %}">지금을 묻다: 역사 퀴즈</li>
          <li class="menu-link" data-url="/posts/category/1/">미래를 잇다: 커뮤니티</li>
          <li class="menu-link" data-url="{% url 'users:mypage' %}">마이페이지</li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main class="main">
      <div class="divider"></div>
      <p>미래를 잇다 아카이빙</p>
      <button class="mypage-btn" id="postListBtn">
        <img
          src="{% static 'home/image/Xnix/Line/card_message.png' %}"
          alt="cardMessage1"
          class="card-icon"
        />
        <img
          src="{% static 'home/image/card_union.png' %}"
          alt="cardUnion"
          class="card-union"
        />
        글 목록 조회
      </button>
      <button class="mypage-btn" id="commentListBtn ">
        <img
          src="{% static 'home/image/Xnix/Line/card_message.png' %}"
          alt="cardMessage2"
          class="card-icon"
        />
        <img
          src="{% static 'home/image/card_union.png' %}"
          alt="cardUnion"
          class="card-union"
        />
        댓글 목록 조회
      </button>
    </main>
    <script src="{% static 'home/js/home.js' %}"></script>
    <script src="{% static 'home/js/mypage.js' %}"></script>
  </body>
</html>

<!-- <h2>내가 쓴 글</h2>
<ul>
  {% for post in my_posts %}
    <li>
      <a href="{% url 'posts:detail' post.id %}">{{ post.title }}</a>
      <small>({{ post.created_at|date:"Y-m-d H:i" }})</small>
    </li>
  {% empty %}
    <li>작성한 게시글이 없습니다.</li>
  {% endfor %}
</ul>

<h2>내가 쓴 댓글</h2>
<ul>
  {% for comment in my_comments %}
    <li>
      "{{ comment.content }}" -
      <a href="{% url 'posts:detail' comment.post.id %}">관련 게시글</a>
      <small>({{ comment.created_at|date:"Y-m-d H:i" }})</small>
    </li>
  {% empty %}
    <li>작성한 댓글이 없습니다.</li>
  {% endfor %}
</ul>

<a href="{% url 'users:mypage' %}">← 마이페이지로 돌아가기</a> -->

herStory/users/templates/users/my_cards.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'home/css/header.css' %}" />
    <link rel="stylesheet" href="{% static 'home/css/person.css' %}" />
    <link rel="stylesheet" href="{% static 'home/css/mypage.css' %}" />
    <link rel="stylesheet" href="{% static 'home/css/peopleView.css' %}" />
  </head>
  <body>
    <header class="header">
      <a href="{% url 'home' %}">
        <img src="{% static 'home/image/mainLogo.svg' %}" class="main-logo" />
      </a>
      <button class="menu-toggle" id="menuToggle">&#9776;</button>
      <nav class="menu" id="menu">
        <ul>
          {% if user.is_authenticated %}
            <li>{{ user.username }}님 환영합니다!</li>
            <li class='menu-link' data-url="{% url 'users:logout' %}">로그아웃</li>
          {% else %}
            <li class='menu-link' data-url="{% url 'users:login' %}">로그인</li>
          {% endif %}
          {% if user.is_authenticated %}
          <div class="divider"></div>
          <li class="menu-link" data-url="{% url 'history:card_intro' %}">과거를 알다: 랜덤 인물 카드</li>
          <li class="menu-link" data-url="{% url 'quizzes:quiz_index' %}">지금을 묻다: 역사 퀴즈</li>
          <li class="menu-link" data-url="/posts/category/1/">미래를 잇다: 커뮤니티</li>
          <li class="menu-link" data-url="{% url 'users:mypage' %}">마이페이지</li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main class="main">
      <div class="divider"></div>
      <p>인물 카드 조회</p>
      <div class="person-list-wrapper">
        <div class="person-list-box">
          {% for saved in saved_cards %}
          <div class="person-row">
            <a href="{% url 'users:my_cards_detail' saved.card.id %}">
              <span class="tag" id="label">이름</span>
              <span class="value">{{ saved.card.name }}</span>
              <span class="tag" id="label">시대</span>
              <span class="value">{{ saved.card.era }}</span>
              <span class="tag" id="label">지역</span>
              <span class="value">{{ saved.card.region }}</span>
            </a>
            <div class="'cardDivider"></div>
          </div>
          {% empty %}
            <p>저장한 카드가 아직 없어요 😢</p>
          {% endfor %}
        </div>
        <!-- 페이지네이션 -->
        <!-- <div class="pagination">
          
          <button class="page-btn-back">&lt;</button>
          <button class="page-btn active">1</button>
          <button class="page-btn">2</button>
          <button class="page-btn">3</button>
          <button class="page-btn">4</button>
          <button class="page-btn">5</button>
          <button class="page-btn-next">&gt;</button>
        </div>
      </div> -->

      <div class="pagination">
        {% if saved_cards.has_previous %}
          <a href="?page={{ saved_cards.previous_page_number }}" class="page-btn-back">&lt;</a>
        {% endif %}

        {% for num in saved_cards.paginator.page_range %}
          {% if saved_cards.number == num %}
            <span class="page-btn active">{{ num }}</span>
          {% else %}
            <a href="?page={{ num }}" class="page-btn">{{ num }}</a>
          {% endif %}
        {% endfor %}

        {% if saved_cards.has_next %}
          <a href="?page={{ saved_cards.next_page_number }}" class="page-btn-next">&gt;</a>
        {% endif %}
      </div>


<!-- <div class="pagination">
  {% if saved_cards.has_previous %}
    <a href="?page={{ saved_cards.previous_page_number }}">«</a>
  {% endif %}

  {% for num in saved_cards.paginator.page_range %}
    {% if saved_cards.number == num %}
      <span class="page-btn active">{{ num }}</span>
    {% else %}
      <a href="?page={{ num }}" class="page-btn">{{ num }}</a>
    {% endif %}
  {% endfor %}

  {% if saved_cards.has_next %}
    <a href="?page={{ saved_cards.next_page_number }}">»</a>
  {% endif %}
</div> -->
      
    </main>
    <script src="{% static 'home/js/home.js' %}"></script>
  </body>
</html>

herStory/users/templates/users/my_cards_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Era Echo - Home</title>
    <link rel="stylesheet" href="{% static 'home/css/header.css' %}" />
    <link rel="stylesheet" href="{% static 'home/css/past.css' %}" />
    <link rel="stylesheet" href="{% static 'home/css/button.css' %}" />
    <link rel="stylesheet" href="{% static 'home/css/peopleCard.css' %}" />
  </head>
  <body>
    <div class="wrapper">
      <header class="header">
        <a href="{% url 'home' %}">
        <img src="{% static 'home/image/mainLogo.svg' %}" class="main-logo" />
        </a>
        <button class="menu-toggle" id="menuToggle">&#9776;</button>
        <nav class="menu" id="menu">
          <ul>
            {% if user.is_authenticated %}
              <li>{{ user.username }}님 환영합니다!</li>
              <li class='menu-link' data-url="{% url 'users:logout' %}">로그아웃</li>
            {% else %}
              <li class='menu-link' data-url="{% url 'users:login' %}">로그인</li>
            {% endif %}
            {% if user.is_authenticated %}
            <div class="divider"></div>
            <li class="menu-link" data-url="{% url 'history:card_intro' %}">과거를 알다: 랜덤 인물 카드</li>
            <li class="menu-link" data-url="{% url 'quizzes:quiz_index' %}">지금을 묻다: 역사 퀴즈</li>
            <li class="menu-link" data-url="/posts/category/1/">미래를 잇다: 커뮤니티</li>
            <li class="menu-link" data-url="{% url 'users:mypage' %}">마이페이지</li>
            {% endif %}
          </ul>
        </nav>
      </header>
      <main class="main">
        <div class="peopleCard">
          <img
            src="{{ card.image_url }}"
            alt="people-img"
            class="people-img"
          />
          <div class="person-info">
            <h3 class="person-name">
              {{ card.name }} <span class="person-date">{{ card.lifespan }}</span>
            </h3>
            <ul class="person-meta">
              <li><span class="label">시대</span> {{ card.era }}</li>
              <li><span class="label">지역</span> {{ card.region }}</li>
              <li>
                <span class="label">설명</span>
                {{ card.description }}
              </li>
            </ul>
          </div>
        </div>
        
        <form method="post" action="{% url 'users:my_cards' %}">
        {% csrf_token %}
        <button class="card-save-btn">
          인물 카드 목록으로 돌아가기
        </button>
        </form>
      </main>
    </div>
    <script src="{% static 'home/js/home.js' %}"></script>
  </body>
</html>

<!-- <h2>{{ card.name }}</h2>
<p>{{ card.lifespan }}</p>
<p>{{ card.era }} / {{ card.region }}</p>
<img src="{{ card.image_url }}" alt="{{ card.name }}" width="200">
<p>{{ card.description }}</p>

<form method="post" action="{% url 'users:my_cards' %}">
  {% csrf_token %}
  <button type="submit">저장한 카드 목록으로 돌아가기</button>
</form> -->

herStory/users/templates/users/mypage.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Era Echo - mypage</title>
    <link rel="stylesheet" href="{% static 'home/css/header.css' %}" />
    <link rel="stylesheet" href="{% static 'home/css/mypage.css' %}" />
    <link rel="stylesheet" href="{% static 'home/css/button.css' %}" />
  </head>
  <body>
    <header class="header">
      <a href="{% url 'home' %}">
        <img src="{% static 'home/image/mainLogo.svg' %}" class="main-logo" />
      </a>
      <button class="menu-toggle" id="menuToggle">&#9776;</button>
      <nav class="menu" id="menu">
        <ul>
          {% if user.is_authenticated %}
            <li>{{ user.username }}님 환영합니다!</li>
            <li class='menu-link' data-url="{% url 'users:logout' %}">로그아웃</li>
          {% else %}
            <li class='menu-link' data-url="{% url 'users:login' %}">로그인</li>
          {% endif %}
          {% if user.is_authenticated %}
          <div class="divider"></div>
          <li class="menu-link" data-url="{% url 'history:card_intro' %}">과거를 알다: 랜덤 인물 카드</li>
          <li class="menu-link" data-url="{% url 'quizzes:quiz_index' %}">지금을 묻다: 역사 퀴즈</li>
          <li class="menu-link" data-url="/posts/category/1/">미래를 잇다: 커뮤니티</li>
          <li class="menu-link" data-url="{% url 'users:mypage' %}">마이페이지</li>
          {% endif %}
        </ul>
      </nav>
    </header>

    <main class="main">
      <div class="divider"></div>
      <p>마이페이지</p>
      {% if user.is_authenticated %}
        <div class="mypage-info">
          <div class="info-row">
            <span class="label">이름</span>
            <span class="value" id="user-name">{{ user.username }}</span>
          </div>
          <div class="info-row">
            <span class="label">계정</span>
            <span class="value" id="user-email">{{ user.email }}</span>
          </div>
        </div>
        <form method="post" action="{% url 'users:my_cards' %}">
        {% csrf_token %}
        <button class="mypage-btn" id="peoplecard">
          <img
            src="{% static 'home/image/card_bookmark.png' %}"
            alt="cardBookmark"
            class="card-icon"
            id="bookMark"
          />
          <img
            src="{% static 'home/image/card_union.png' %}"
            alt="cardUnion"
            class="card-union"
            id="cardIcon"
          />
          인물 카드 조회
        </button>
        </form>
        <button class="mypage-btn" id="withdrawBtn">
          <img
            src="{% static 'home/image/Xnix/Line/card_member.png' %}"
            alt="cardBookmark"
            class="card-icon"
            id="bookMark2"
          />
          <img
            src="{% static 'home/image/card_union.png' %}"
            alt="cardUnion"
            class="card-union"
            id="cardIcon2"
          />
          회원 탈퇴
        </button>
      {% else %}
        <p>로그인이 필요합니다.</p>
      {% endif %}
      <!-- 탈퇴 확인 모달 -->
      <div id="modalOverlay" class="modal-overlay hidden">
        <div class="modal-box">
          <h3>회원 탈퇴를 하시겠습니까?</h3>
          <div class="modal-buttons">
            <button id="cancelBtn" class="modal-btn cancel">취소</button>
            <form method="post" action="{% url 'users:delete_account' %}">
            {% csrf_token %}
            <button id="confirmBtn" class="modal-btn confirm">확인</button>
            </form>
          </div>
        </div>
      </div>
    </main>
    <script src="{% static 'home/js/withdraw.js' %}"></script>
    <script src="{% static 'home/js/home.js' %}"></script>
    <script src="{% static 'home/js/mypage.js' %}"></script>
  </body>
</html>